#!/bin/bash

set -euo pipefail

export K8S_NODE_OS=${K8S_NODE_OS:-ubuntu}
export K8S_WORKERS=${K8S_WORKERS:-1}
export VAGRANT_DEFAULT_PROVIDER=${VAGRANT_DEFAULT_PROVIDER:-virtualbox}
export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"1.11.9"}

if [ -f .vagrant-state ]; then
  . .vagrant-state
fi

vagrant up
